### ISSUE TITLE
nextjs

### ISSUE THREAD

**Issue by alu0101056944** [ULL-MII-SYTWS-2324/nextjs-marcos-barrios-lorenzo-alu0101056944#4]

**Comment by alu0101056944** [comment]
No estoy seguro de qué es lo que se pide exactamente pero he partido de la práctica anterior de este año y he extendido la página web con un botón de enviar, además de modificar un poco su estilo. Hice deploy de un for a vercel: https://nextjs-marcos-barrios-lorenzo-alu0101056944.vercel.app
Sigo sin tener un token de OpenAI por lo que no puedo comprobar el funcionamiento final.
@crguezl

**Comment by crguezl** [comment]
@alu0101056944  excelente!
